- name: Install Maven on Ubuntu 20
  become: true
  # hosts: 127.0.0.1
  hosts: all
  roles:
    - maven-ubuntu-20
  vars:
    ansible_host: 127.0.0.1
    ansible_user: ionut-alexandru
    maven_version: "3.2.5"